--- #YAML:1.0
name:                OIS
version:             0.04
abstract:            Perl binding for the OIS C++ input framework
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Scalar::Util:                  1.18
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Scott Lanning <slanning@cpan.org>
